on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server via SSH
        env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            set -e
      
            echo 'ğŸ”´ Deleting old PM2 process (if exists)...'
            pm2 delete sozly-job || echo 'No existing PM2 process'
      
            echo 'ğŸ§¹ Removing old project folder...'
            rm -rf /root/backend/sozly-job
      
            echo 'ğŸ“¥ Cloning fresh repo...'
            git clone git@github.com:memmedov-karim/sozly-job.git /root/backend/sozly-job
      
            cd /root/backend/sozly-job
      
            echo 'ğŸ“ Creating .env file from GitHub secret...'
            echo \"$ENV_FILE\" > .env
      
            echo 'ğŸ“¦ Installing dependencies...'
            npm install
      
            echo 'ğŸ›  Building TypeScript project...'
            npm run build
      
            echo 'ğŸš€ Starting app with PM2 using cluster script...'
            pm2 start dist/index.js --name sozly-job
      
            echo 'ğŸ’¾ Saving PM2 process list...'
            pm2 save
          "